INSERT INTO paciente (nombre, apellido, correo, telefono, direccion, fecha_nacimiento)
SELECT * FROM (
    SELECT 'Carlos'    as nombre, 'Martinez'  as apellido, 'carlos.martinez@gmail.com'   as correo, '55501001' as telefono, 'Av. Central 101'      as direccion, '1985-03-12' as fecha_nacimiento UNION ALL
    SELECT 'Ana',                 'Lopez',                 'ana.lopez@gmail.com',                   '55501002',              'Calle 5 #22',                       '1990-07-24'                      UNION ALL
    SELECT 'Luis',                'Garcia',                'luis.garcia@gmail.com',                 '55501003',              'Blvd. Norte 300',                   '1978-11-05'                      UNION ALL
    SELECT 'Maria',               'Hernandez',             'maria.hernandez@gmail.com',             '55501004',              'Col. Centro 44',                    '1995-01-18'                      UNION ALL
    SELECT 'Jorge',               'Perez',                 'jorge.perez@gmail.com',                 '55501005',              'Calle 8 #15',                       '1982-06-30'                      UNION ALL
    SELECT 'Laura',               'Sanchez',               'laura.sanchez@gmail.com',               '55501006',              'Av. Sur 210',                       '1993-09-14'                      UNION ALL
    SELECT 'Miguel',              'Ramirez',               'miguel.ramirez@gmail.com',              '55501007',              'Calle 12 #88',                      '1975-04-22'                      UNION ALL
    SELECT 'Sofia',               'Torres',                'sofia.torres@gmail.com',                '55501008',              'Col. Las Flores 9',                 '1998-12-03'                      UNION ALL
    SELECT 'Roberto',             'Flores',                'roberto.flores@gmail.com',              '55501009',              'Av. Oriente 77',                    '1988-08-16'                      UNION ALL
    SELECT 'Valentina',           'Diaz',                  'valentina.diaz@gmail.com',              '55501010',              'Blvd. Reforma 55',                  '1996-02-27'                      UNION ALL
    SELECT 'Fernando',            'Morales',               'fernando.morales@gmail.com',            '55501011',              'Calle 3 #40',                       '1980-05-09'                      UNION ALL
    SELECT 'Isabella',            'Jimenez',               'isabella.jimenez@gmail.com',            '55501012',              'Av. Juarez 18',                     '1992-10-21'                      UNION ALL
    SELECT 'Andres',              'Ruiz',                  'andres.ruiz@gmail.com',                 '55501013',              'Col. Moderna 66',                   '1987-07-07'                      UNION ALL
    SELECT 'Camila',              'Vargas',                'camila.vargas@gmail.com',               '55501014',              'Calle 20 #5',                       '1994-03-31'                      UNION ALL
    SELECT 'Diego',               'Castro',                'diego.castro@gmail.com',                '55501015',              'Av. Independencia 90',              '1983-01-15'                      UNION ALL
    SELECT 'Lucia',               'Ortiz',                 'lucia.ortiz@gmail.com',                 '55501016',              'Blvd. Sur 33',                      '1997-06-08'                      UNION ALL
    SELECT 'Pablo',               'Mendoza',               'pablo.mendoza@gmail.com',               '55501017',              'Calle 7 #12',                       '1976-09-19'                      UNION ALL
    SELECT 'Gabriela',            'Cruz',                  'gabriela.cruz@gmail.com',               '55501018',              'Col. Jardines 4',                   '1991-11-28'                      UNION ALL
    SELECT 'Sebastian',           'Reyes',                 'sebastian.reyes@gmail.com',             '55501019',              'Av. Libertad 67',                   '1986-04-04'                      UNION ALL
    SELECT 'Daniela',             'Moreno',                'daniela.moreno@gmail.com',              '55501020',              'Calle 15 #99',                      '1999-08-11'
) WHERE NOT EXISTS (SELECT 1 FROM paciente LIMIT 1);

DELETE FROM medico;

INSERT INTO medico (run_medico, nombre, apellido, especialidad, jefe_turno, correo)
SELECT * FROM (
    SELECT 15234871 as run_medico, 'Ricardo'   as nombre, 'Fuentes'   as apellido, 'Cardiologia'    as especialidad, 'Dr. Alvaro Soto'     as jefe_turno, 'ricardo.fuentes@hospital.cl'   as correo UNION ALL
    SELECT 12087453,               'Patricia',             'Vega',                  'Neurologia',                    'Dra. Carmen Reyes',                 'patricia.vega@hospital.cl'              UNION ALL
    SELECT 18356204,               'Hector',               'Salinas',               'Pediatria',                     'Dr. Mauricio Lagos',                'hector.salinas@hospital.cl'             UNION ALL
    SELECT 11492637,               'Claudia',              'Mora',                  'Dermatologia',                  'Dra. Isabel Pinto',                 'claudia.mora@hospital.cl'               UNION ALL
    SELECT 16783041,               'Andres',               'Pinto',                 'Traumatologia',                 'Dr. Roberto Vera',                  'andres.pinto@hospital.cl'               UNION ALL
    SELECT 13920485,               'Valentina',            'Rios',                  'Ginecologia',                   'Dra. Monica Tapia',                 'valentina.rios@hospital.cl'             UNION ALL
    SELECT 17641329,               'Marcos',               'Ibanez',                'Oftalmologia',                  'Dr. Cristian Moya',                 'marcos.ibanez@hospital.cl'              UNION ALL
    SELECT 10258763,               'Daniela',              'Cerda',                 'Psiquiatria',                   'Dra. Andrea Nunez',                 'daniela.cerda@hospital.cl'              UNION ALL
    SELECT 19374856,               'Felipe',               'Araya',                 'Urologia',                      'Dr. Gonzalo Bravo',                 'felipe.araya@hospital.cl'               UNION ALL
    SELECT 14502918,               'Javiera',              'Munoz',                 'Endocrinologia',                'Dra. Lorena Castro',                'javiera.munoz@hospital.cl'
);

INSERT INTO citamedica (fecha, hora, costo, diagnostico, correo, paciente_id, medico_id)
SELECT fecha, hora, costo, diagnostico, correo, paciente_id, medico_id FROM (
    SELECT '2026-01-08' as fecha, '09:00:00' as hora, 35000.0 as costo, 'Hipertension leve'          as diagnostico, 'cita01@hospital.cl' as correo, (SELECT id FROM paciente WHERE nombre='Carlos'    AND apellido='Martinez') as paciente_id, (SELECT id FROM medico WHERE nombre='Ricardo'   AND apellido='Fuentes') as medico_id UNION ALL
    SELECT '2026-01-09',          '10:00:00',          28000.0,          'Migraña cronica',                          'cita02@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Ana'       AND apellido='Lopez'),                         (SELECT id FROM medico WHERE nombre='Patricia'  AND apellido='Vega')                 UNION ALL
    SELECT '2026-01-10',          '11:00:00',          22000.0,          'Fiebre y tos',                             'cita03@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Luis'      AND apellido='Garcia'),                        (SELECT id FROM medico WHERE nombre='Hector'    AND apellido='Salinas')             UNION ALL
    SELECT '2026-01-13',          '08:30:00',          31000.0,          'Dermatitis alergica',                      'cita04@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Maria'     AND apellido='Hernandez'),                     (SELECT id FROM medico WHERE nombre='Claudia'   AND apellido='Mora')                UNION ALL
    SELECT '2026-01-14',          '14:00:00',          45000.0,          'Fractura de muñeca',                       'cita05@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Jorge'     AND apellido='Perez'),                         (SELECT id FROM medico WHERE nombre='Andres'    AND apellido='Pinto')               UNION ALL
    SELECT '2026-01-15',          '15:30:00',          38000.0,          'Control prenatal',                         'cita06@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Laura'     AND apellido='Sanchez'),                       (SELECT id FROM medico WHERE nombre='Valentina' AND apellido='Rios')               UNION ALL
    SELECT '2026-01-16',          '09:30:00',          27000.0,          'Vision borrosa',                           'cita07@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Miguel'    AND apellido='Ramirez'),                       (SELECT id FROM medico WHERE nombre='Marcos'    AND apellido='Ibanez')              UNION ALL
    SELECT '2026-01-17',          '16:00:00',          52000.0,          'Ansiedad y depresion',                     'cita08@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Sofia'     AND apellido='Torres'),                        (SELECT id FROM medico WHERE nombre='Daniela'   AND apellido='Cerda')               UNION ALL
    SELECT '2026-01-20',          '10:30:00',          33000.0,          'Infeccion urinaria',                       'cita09@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Roberto'   AND apellido='Flores'),                        (SELECT id FROM medico WHERE nombre='Felipe'    AND apellido='Araya')               UNION ALL
    SELECT '2026-01-21',          '11:30:00',          41000.0,          'Diabetes tipo 2',                          'cita10@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Valentina' AND apellido='Diaz'),                          (SELECT id FROM medico WHERE nombre='Javiera'   AND apellido='Munoz')               UNION ALL
    SELECT '2026-01-22',          '08:00:00',          36000.0,          'Arritmia cardiaca',                        'cita11@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Fernando'  AND apellido='Morales'),                       (SELECT id FROM medico WHERE nombre='Ricardo'   AND apellido='Fuentes')             UNION ALL
    SELECT '2026-01-23',          '13:00:00',          29000.0,          'Dolor de cabeza cronico',                  'cita12@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Isabella'  AND apellido='Jimenez'),                       (SELECT id FROM medico WHERE nombre='Patricia'  AND apellido='Vega')                UNION ALL
    SELECT '2026-01-24',          '15:00:00',          24000.0,          'Control pediatrico',                       'cita13@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Andres'    AND apellido='Ruiz'),                          (SELECT id FROM medico WHERE nombre='Hector'    AND apellido='Salinas')             UNION ALL
    SELECT '2026-01-27',          '09:00:00',          48000.0,          'Esguince de tobillo',                      'cita14@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Camila'    AND apellido='Vargas'),                        (SELECT id FROM medico WHERE nombre='Andres'    AND apellido='Pinto')               UNION ALL
    SELECT '2026-01-28',          '10:00:00',          55000.0,          'Hipotiroidismo',                           'cita15@hospital.cl',             (SELECT id FROM paciente WHERE nombre='Diego'     AND apellido='Castro'),                        (SELECT id FROM medico WHERE nombre='Javiera'   AND apellido='Munoz')
) WHERE NOT EXISTS (SELECT 1 FROM citamedica LIMIT 1);
