spring.datasource.url=jdbc:sqlite:Hospital.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/migration/V2__insert_data.sql
spring.jpa.defer-datasource-initialization=true
